// Armature Generator Library for Stop-Motion Puppets
// Generates Python scripts for Blender to create 3D-printable armatures

export interface ArmatureSettings {
  // Basic dimensions
  height: number; // Total puppet height in mm (100, 150, 200, 250, 300)
  
  // Joint settings
  jointDiameter: number; // Ball joint diameter in mm (3, 4, 5, 6)
  jointType: 'ball-and-socket' | 'hinge';
  
  // Hand settings
  fingerCount: 3 | 4 | 5;
  
  // Additional features
  includeEars: boolean;
  includeTail: boolean;
  
  // SLA printing settings
  printGap: number; // Gap between moving parts (0.2-0.3mm)
  minWallThickness: number; // Minimum wall thickness (0.8mm)
}

export interface ArmaturePreset {
  id: string;
  name: string;
  nameRu: string;
  description: string;
  descriptionRu: string;
  settings: Partial<ArmatureSettings>;
  type: 'simple' | 'professional' | 'mini';
}

// Default settings based on puppet height
export function getDefaultSettings(height: number): Partial<ArmatureSettings> {
  const scale = height / 200; // Base scale on 200mm puppet
  return {
    height,
    jointDiameter: Math.round(4 * scale) as 3 | 4 | 5 | 6,
    jointType: 'ball-and-socket',
    fingerCount: 4,
    includeEars: false,
    includeTail: false,
    printGap: 0.25,
    minWallThickness: 0.8,
  };
}

// Available presets
export const ARMATURE_PRESETS: ArmaturePreset[] = [
  {
    id: 'simple-humanoid',
    name: 'Simple Humanoid',
    nameRu: 'Базовый гуманоидный каркас',
    description: 'Basic armature with simple ball joints for beginners',
    descriptionRu: 'Простой скелет с шарнирами для начинающих',
    settings: {
      height: 200,
      jointDiameter: 4,
      jointType: 'ball-and-socket',
      fingerCount: 4,
      includeEars: false,
      includeTail: false,
      printGap: 0.25,
      minWallThickness: 0.8,
    },
    type: 'simple',
  },
  {
    id: 'professional-ball-socket',
    name: 'Professional Ball & Socket',
    nameRu: 'Профессиональный каркас с ball-and-socket joints',
    description: 'Professional armature with high-quality spherical joints',
    descriptionRu: 'Профессиональный каркас с качественными сферическими шарнирами',
    settings: {
      height: 250,
      jointDiameter: 5,
      jointType: 'ball-and-socket',
      fingerCount: 5,
      includeEars: false,
      includeTail: false,
      printGap: 0.2,
      minWallThickness: 1.0,
    },
    type: 'professional',
  },
  {
    id: 'mini-puppet',
    name: 'Mini Puppet',
    nameRu: 'Мини-каркас для простой куклы',
    description: 'Simplified armature for small puppets',
    descriptionRu: 'Упрощённая версия для маленьких кукол',
    settings: {
      height: 100,
      jointDiameter: 3,
      jointType: 'ball-and-socket',
      fingerCount: 3,
      includeEars: false,
      includeTail: false,
      printGap: 0.3,
      minWallThickness: 0.8,
    },
    type: 'mini',
  },
];

// Scale factors based on puppet height
export function getScaleFactors(height: number) {
  const baseHeight = 200; // Reference height in mm
  const scale = height / baseHeight;
  
  return {
    scale,
    // Body proportions (in mm, scaled)
    headDiameter: 25 * scale,
    neckLength: 12 * scale,
    neckDiameter: 8 * scale,
    
    // Torso
    torsoLength: 50 * scale,
    torsoWidth: 30 * scale,
    ribCageDepth: 15 * scale,
    
    // Arms
    upperArmLength: 30 * scale,
    lowerArmLength: 28 * scale,
    armDiameter: 6 * scale,
    
    // Hands
    handLength: 12 * scale,
    handWidth: 10 * scale,
    fingerLength: 10 * scale,
    fingerDiameter: 2 * scale,
    
    // Legs
    upperLegLength: 35 * scale,
    lowerLegLength: 35 * scale,
    legDiameter: 8 * scale,
    
    // Feet
    footLength: 20 * scale,
    footWidth: 10 * scale,
    footHeight: 6 * scale,
    
    // Joint parameters
    ballRadius: 0, // Will be calculated from jointDiameter
    socketDepth: 0,
    socketWallThickness: 0, 
  };
}

// Generate Blender Python script
export function generateBlenderScript(settings: ArmatureSettings): string {
  const scales = getScaleFactors(settings.height);
  const jointRadius = settings.jointDiameter / 2;
  const gap = settings.printGap;
  
  return `# Blender Python Script for Stop-Motion Puppet Armature
# Generated by Armature Generator
# Puppet Height: ${settings.height}mm
# Joint Type: ${settings.jointType}
# Joint Diameter: ${settings.jointDiameter}mm
# Print Gap: ${settings.printGap}mm

import bpy
import math
from mathutils import Vector, Matrix

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

# ============================================================================
# CONFIGURATION
# ============================================================================
PUPPET_HEIGHT = ${settings.height}  # mm
JOINT_DIAMETER = ${settings.jointDiameter}  # mm
JOINT_RADIUS = JOINT_DIAMETER / 2
PRINT_GAP = ${settings.printGap}  # Gap between moving parts for SLA printing
MIN_WALL_THICKNESS = ${settings.minWallThickness}  # mm
FINGER_COUNT = ${settings.fingerCount}
INCLUDE_EARS = ${settings.includeEars}
INCLUDE_TAIL = ${settings.includeTail}
JOINT_TYPE = "${settings.jointType}"

# Scale factors
SCALE = PUPPET_HEIGHT / 200

# Joint parameters
BALL_RADIUS = JOINT_RADIUS
SOCKET_INNER_RADIUS = BALL_RADIUS + PRINT_GAP
SOCKET_OUTER_RADIUS = SOCKET_INNER_RADIUS + MIN_WALL_THICKNESS
SOCKET_DEPTH = BALL_RADIUS * 0.8

# Bone parameters
BONE_DIAMETER = 4 * SCALE
TIE_ROD_DIAMETER = 2 * SCALE

# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def create_material(name, color):
    """Create a new material with given color"""
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs['Base Color'].default_value = (*color, 1.0)
    bsdf.inputs['Metallic'].default_value = 0.3
    bsdf.inputs['Roughness'].default_value = 0.4
    return mat

def create_ball_joint(location, name, ball_mat, socket_mat):
    """Create a ball-and-socket joint at given location"""
    # Create ball (sphere)
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=BALL_RADIUS,
        location=location
    )
    ball = bpy.context.active_object
    ball.name = f"{name}_ball"
    ball.data.materials.append(ball_mat)
    
    # Create socket (hollow sphere segment)
    bpy.ops.mesh.primitive_cylinder_add(
        radius=SOCKET_OUTER_RADIUS,
        depth=SOCKET_OUTER_RADIUS * 2,
        location=location
    )
    socket = bpy.context.active_object
    socket.name = f"{name}_socket"
    
    # Create inner cutout for socket
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=SOCKET_INNER_RADIUS,
        location=location
    )
    inner_sphere = bpy.context.active_object
    
    # Boolean difference for socket
    modifier = socket.modifiers.new(name="Hollow", type='BOOLEAN')
    modifier.object = inner_sphere
    modifier.operation = 'DIFFERENCE'
    
    # Apply modifier and delete inner sphere
    bpy.context.view_layer.objects.active = socket
    bpy.ops.object.modifier_apply(modifier="Hollow")
    bpy.data.objects.remove(inner_sphere, do_unlink=True)
    
    socket.data.materials.append(socket_mat)
    
    return ball, socket

def create_hinge_joint(location, rotation, name, hinge_mat):
    """Create a hinge joint at given location with rotation"""
    # Create hinge cylinder
    bpy.ops.mesh.primitive_cylinder_add(
        radius=BALL_RADIUS,
        depth=BALL_RADIUS * 1.5,
        location=location,
        rotation=rotation
    )
    hinge_outer = bpy.context.active_object
    hinge_outer.name = f"{name}_hinge_outer"
    hinge_outer.data.materials.append(hinge_mat)
    
    # Create inner hole
    inner_radius = BALL_RADIUS * 0.5 + PRINT_GAP
    bpy.ops.mesh.primitive_cylinder_add(
        radius=inner_radius,
        depth=BALL_RADIUS * 2,
        location=location,
        rotation=rotation
    )
    hinge_inner = bpy.context.active_object
    
    # Boolean difference
    modifier = hinge_outer.modifiers.new(name="Hole", type='BOOLEAN')
    modifier.object = hinge_inner
    modifier.operation = 'DIFFERENCE'
    
    bpy.context.view_layer.objects.active = hinge_outer
    bpy.ops.object.modifier_apply(modifier="Hole")
    bpy.data.objects.remove(hinge_inner, do_unlink=True)
    
    return hinge_outer

def create_bone(start, end, diameter, name, material):
    """Create a bone/link between two points"""
    direction = Vector(end) - Vector(start)
    length = direction.length
    center = [(start[0] + end[0])/2, (start[1] + end[1])/2, (start[2] + end[2])/2]
    
    # Create cylinder for bone
    bpy.ops.mesh.primitive_cylinder_add(
        radius=diameter/2,
        depth=length,
        location=center
    )
    bone = bpy.context.active_object
    bone.name = name
    
    # Rotate to align with direction
    direction.normalize()
    up = Vector((0, 0, 1))
    angle = math.acos(direction.dot(up))
    axis = up.cross(direction).normalized()
    if axis.length > 0:
        bone.rotation_mode = 'AXIS_ANGLE'
        bone.rotation_axis_angle = (angle, axis.x, axis.y, axis.z)
    
    bone.data.materials.append(material)
    return bone

def create_flat_base(obj, z_offset=0):
    """Add flat base for better 3D printing"""
    # Add a thin flat base under the object
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.transform.translate(value=(0, 0, z_offset))
    bpy.ops.object.mode_set(mode='OBJECT')

def add_resin_drain_holes(obj, hole_diameter=2):
    """Add small holes for resin drainage in SLA printing"""
    bpy.context.view_layer.objects.active = obj
    # This would add small holes - simplified for now
    pass

# ============================================================================
# MATERIALS
# ============================================================================

# Different colors for different parts for easy identification
BALL_MATERIAL = create_material("Ball_Joint", (0.8, 0.2, 0.2))  # Red
SOCKET_MATERIAL = create_material("Socket_Joint", (0.2, 0.6, 0.8))  # Blue
BONE_MATERIAL = create_material("Bone", (0.6, 0.6, 0.6))  # Gray
HAND_MATERIAL = create_material("Hand", (0.9, 0.7, 0.3))  # Yellow
FOOT_MATERIAL = create_material("Foot", (0.3, 0.8, 0.3))  # Green

# ============================================================================
# ARMATURE CONSTRUCTION
# ============================================================================

# Body positions (centered at origin, feet on ground)
# All measurements in mm

# Calculate positions based on scale
head_pos = (0, 0, PUPPET_HEIGHT * 0.9)
neck_pos = (0, 0, PUPPET_HEIGHT * 0.78)
shoulder_center = (0, 0, PUPPET_HEIGHT * 0.75)
spine_top = (0, 0, PUPPET_HEIGHT * 0.72)
spine_mid = (0, 0, PUPPET_HEIGHT * 0.55)
hip_center = (0, 0, PUPPET_HEIGHT * 0.45)
pelvis = (0, 0, PUPPET_HEIGHT * 0.40)

# Shoulder positions
shoulder_width = 35 * SCALE
left_shoulder = (-shoulder_width/2, 0, PUPPET_HEIGHT * 0.73)
right_shoulder = (shoulder_width/2, 0, PUPPET_HEIGHT * 0.73)

# Arm positions
left_elbow = (-shoulder_width/2 - 5*SCALE, 0, PUPPET_HEIGHT * 0.58)
right_elbow = (shoulder_width/2 + 5*SCALE, 0, PUPPET_HEIGHT * 0.58)
left_wrist = (-shoulder_width/2 - 8*SCALE, 0, PUPPET_HEIGHT * 0.43)
right_wrist = (shoulder_width/2 + 8*SCALE, 0, PUPPET_HEIGHT * 0.43)

# Hip positions
hip_width = 20 * SCALE
left_hip = (-hip_width/2, 0, PUPPET_HEIGHT * 0.42)
right_hip = (hip_width/2, 0, PUPPET_HEIGHT * 0.42)

# Leg positions
left_knee = (-hip_width/2, 0, PUPPET_HEIGHT * 0.25)
right_knee = (hip_width/2, 0, PUPPET_HEIGHT * 0.25)
left_ankle = (-hip_width/2, 0, PUPPET_HEIGHT * 0.08)
right_ankle = (hip_width/2, 0, PUPPET_HEIGHT * 0.08)

# Foot positions
left_foot = (-hip_width/2, 5*SCALE, 0)
right_foot = (hip_width/2, 5*SCALE, 0)

# ============================================================================
# BUILD SKELETON
# ============================================================================

print("Building armature skeleton...")

# Spine bones
create_bone(head_pos, neck_pos, BONE_DIAMETER, "neck_bone", BONE_MATERIAL)
create_bone(neck_pos, spine_top, BONE_DIAMETER, "upper_spine", BONE_MATERIAL)
create_bone(spine_top, spine_mid, BONE_DIAMETER, "mid_spine", BONE_MATERIAL)
create_bone(spine_mid, hip_center, BONE_DIAMETER * 1.2, "lower_spine", BONE_MATERIAL)

# Head (simplified sphere)
bpy.ops.mesh.primitive_uv_sphere_add(
    radius=12*SCALE,
    location=head_pos
)
head = bpy.context.active_object
head.name = "head"
head.data.materials.append(BONE_MATERIAL)

# Shoulders
create_bone(left_shoulder, right_shoulder, BONE_DIAMETER, "shoulder_bridge", BONE_MATERIAL)

# Arms
create_bone(left_shoulder, left_elbow, BONE_DIAMETER * 0.8, "left_upper_arm", BONE_MATERIAL)
create_bone(left_elbow, left_wrist, BONE_DIAMETER * 0.7, "left_lower_arm", BONE_MATERIAL)
create_bone(right_shoulder, right_elbow, BONE_DIAMETER * 0.8, "right_upper_arm", BONE_MATERIAL)
create_bone(right_elbow, right_wrist, BONE_DIAMETER * 0.7, "right_lower_arm", BONE_MATERIAL)

# Legs
create_bone(left_hip, left_knee, BONE_DIAMETER, "left_upper_leg", BONE_MATERIAL)
create_bone(left_knee, left_ankle, BONE_DIAMETER * 0.9, "left_lower_leg", BONE_MATERIAL)
create_bone(right_hip, right_knee, BONE_DIAMETER, "right_upper_leg", BONE_MATERIAL)
create_bone(right_knee, right_ankle, BONE_DIAMETER * 0.9, "right_lower_leg", BONE_MATERIAL)

# Hip bridge
create_bone(left_hip, right_hip, BONE_DIAMETER * 1.2, "hip_bridge", BONE_MATERIAL)

# ============================================================================
# BALL JOINTS (if selected)
# ============================================================================

if JOINT_TYPE == "ball-and-socket":
    print("Creating ball-and-socket joints...")
    
    # Neck joint
    create_ball_joint(neck_pos, "neck", BALL_MATERIAL, SOCKET_MATERIAL)
    
    # Shoulder joints
    create_ball_joint(left_shoulder, "left_shoulder", BALL_MATERIAL, SOCKET_MATERIAL)
    create_ball_joint(right_shoulder, "right_shoulder", BALL_MATERIAL, SOCKET_MATERIAL)
    
    # Elbow joints
    create_ball_joint(left_elbow, "left_elbow", BALL_MATERIAL, SOCKET_MATERIAL)
    create_ball_joint(right_elbow, "right_elbow", BALL_MATERIAL, SOCKET_MATERIAL)
    
    # Wrist joints
    create_ball_joint(left_wrist, "left_wrist", BALL_MATERIAL, SOCKET_MATERIAL)
    create_ball_joint(right_wrist, "right_wrist", BALL_MATERIAL, SOCKET_MATERIAL)
    
    # Hip joints
    create_ball_joint(left_hip, "left_hip", BALL_MATERIAL, SOCKET_MATERIAL)
    create_ball_joint(right_hip, "right_hip", BALL_MATERIAL, SOCKET_MATERIAL)
    
    # Knee joints
    create_ball_joint(left_knee, "left_knee", BALL_MATERIAL, SOCKET_MATERIAL)
    create_ball_joint(right_knee, "right_knee", BALL_MATERIAL, SOCKET_MATERIAL)
    
    # Ankle joints
    create_ball_joint(left_ankle, "left_ankle", BALL_MATERIAL, SOCKET_MATERIAL)
    create_ball_joint(right_ankle, "right_ankle", BALL_MATERIAL, SOCKET_MATERIAL)

# ============================================================================
# HINGE JOINTS (if selected)
# ============================================================================

if JOINT_TYPE == "hinge":
    print("Creating hinge joints...")
    
    # Hinge rotation (aligned with X axis)
    hinge_rot = (math.pi/2, 0, 0)
    
    # Create hinge joints at key locations
    create_hinge_joint(left_elbow, hinge_rot, "left_elbow", SOCKET_MATERIAL)
    create_hinge_joint(right_elbow, hinge_rot, "right_elbow", SOCKET_MATERIAL)
    create_hinge_joint(left_knee, hinge_rot, "left_knee", SOCKET_MATERIAL)
    create_hinge_joint(right_knee, hinge_rot, "right_knee", SOCKET_MATERIAL)

# ============================================================================
# HANDS WITH FINGERS
# ============================================================================

print("Creating hands with fingers...")

def create_hand(wrist_pos, side, finger_count):
    """Create a hand with specified number of fingers"""
    hand_center = (
        wrist_pos[0] + (5*SCALE if side == "left" else -5*SCALE),
        wrist_pos[1],
        wrist_pos[2] - 8*SCALE
    )
    
    # Palm
    bpy.ops.mesh.primitive_cube_add(
        size=1,
        location=hand_center,
        scale=(8*SCALE, 3*SCALE, 6*SCALE)
    )
    palm = bpy.context.active_object
    palm.name = f"{side}_palm"
    palm.data.materials.append(HAND_MATERIAL)
    
    # Fingers
    finger_spacing = 3 * SCALE
    start_x = hand_center[0] - (finger_count - 1) * finger_spacing / 2
    
    for i in range(finger_count):
        finger_x = start_x + i * finger_spacing
        finger_base = (finger_x, hand_center[1], hand_center[2] - 3*SCALE)
        finger_tip = (finger_x, hand_center[1], hand_center[2] - 12*SCALE)
        create_bone(finger_base, finger_tip, 2*SCALE, f"{side}_finger_{i+1}", HAND_MATERIAL)
        
        # Finger tip ball
        bpy.ops.mesh.primitive_uv_sphere_add(
            radius=1.2*SCALE,
            location=finger_tip
        )
        tip = bpy.context.active_object
        tip.name = f"{side}_finger_{i+1}_tip"
        tip.data.materials.append(HAND_MATERIAL)
    
    # Thumb (opposite side)
    thumb_base = (
        hand_center[0] + (3*SCALE if side == "left" else -3*SCALE),
        hand_center[1] + 3*SCALE,
        hand_center[2]
    )
    thumb_tip = (thumb_base[0], thumb_base[1] + 5*SCALE, thumb_base[2] - 5*SCALE)
    create_bone(thumb_base, thumb_tip, 2*SCALE, f"{side}_thumb", HAND_MATERIAL)

create_hand(left_wrist, "left", FINGER_COUNT)
create_hand(right_wrist, "right", FINGER_COUNT)

# ============================================================================
# FEET WITH TIE-DOWN POINTS
# ============================================================================

print("Creating feet with tie-down points...")

def create_foot(ankle_pos, side):
    """Create a foot with tie-down hole"""
    foot_center = (
        ankle_pos[0],
        ankle_pos[1] + 8*SCALE,
        3*SCALE
    )
    
    # Foot base
    bpy.ops.mesh.primitive_cube_add(
        size=1,
        location=foot_center,
        scale=(10*SCALE, 20*SCALE, 6*SCALE)
    )
    foot = bpy.context.active_object
    foot.name = f"{side}_foot"
    foot.data.materials.append(FOOT_MATERIAL)
    
    # Tie-down hole
    hole_radius = 2 * SCALE
    bpy.ops.mesh.primitive_cylinder_add(
        radius=hole_radius,
        depth=8*SCALE,
        location=(foot_center[0], foot_center[1] - 5*SCALE, foot_center[2])
    )
    hole = bpy.context.active_object
    
    # Boolean difference
    modifier = foot.modifiers.new(name="TieDownHole", type='BOOLEAN')
    modifier.object = hole
    modifier.operation = 'DIFFERENCE'
    
    bpy.context.view_layer.objects.active = foot
    bpy.ops.object.modifier_apply(modifier="TieDownHole")
    bpy.data.objects.remove(hole, do_unlink=True)

create_foot(left_ankle, "left")
create_foot(right_ankle, "right")

# ============================================================================
# OPTIONAL FEATURES
# ============================================================================

if INCLUDE_EARS:
    print("Adding ears...")
    # Ear positions
    left_ear_pos = (-10*SCALE, 0, PUPPET_HEIGHT * 0.92)
    right_ear_pos = (10*SCALE, 0, PUPPET_HEIGHT * 0.92)
    
    for pos, side in [(left_ear_pos, "left"), (right_ear_pos, "right")]:
        bpy.ops.mesh.primitive_cone_add(
            radius1=3*SCALE,
            radius2=0,
            depth=8*SCALE,
            location=pos,
            rotation=(0, math.pi/6 if side == "left" else -math.pi/6, 0)
        )
        ear = bpy.context.active_object
        ear.name = f"{side}_ear"
        ear.data.materials.append(BONE_MATERIAL)

if INCLUDE_TAIL:
    print("Adding tail...")
    tail_base = (0, -8*SCALE, PUPPET_HEIGHT * 0.38)
    
    # Create tail segments
    tail_points = [
        tail_base,
        (0, -15*SCALE, PUPPET_HEIGHT * 0.35),
        (0, -22*SCALE, PUPPET_HEIGHT * 0.30),
        (0, -28*SCALE, PUPPET_HEIGHT * 0.22),
        (0, -32*SCALE, PUPPET_HEIGHT * 0.12),
    ]
    
    for i in range(len(tail_points) - 1):
        create_bone(
            tail_points[i],
            tail_points[i+1],
            BONE_DIAMETER * (1 - i*0.15),
            f"tail_segment_{i+1}",
            BONE_MATERIAL
        )

# ============================================================================
# ORGANIZE INTO COLLECTIONS FOR PRINTING
# ============================================================================

print("Organizing parts into collections...")

# Create collections for organized printing
def create_collection(name):
    if name not in bpy.data.collections:
        return bpy.data.collections.new(name)
    return bpy.data.collections[name]

# Create separate collections for different print orientations
balls_collection = create_collection("Balls_Print_Down")
sockets_collection = create_collection("Sockets_Print_Up")  
bones_collection = create_collection("Bones_Print_Flat")
hands_collection = create_collection("Hands_Print_Palm_Down")
feet_collection = create_collection("Feet_Print_Sole_Down")

# ============================================================================
# PRINTING PREPARATION NOTES
# ============================================================================

print("""
========================================
ARMATURE GENERATION COMPLETE!
========================================

Print Settings Recommendations:
- Layer height: 0.05mm for best detail
- Exposure: Follow resin manufacturer guidelines
- Orientation: Print balls with support point at top
- Sockets: Print with opening facing up

Assembly Notes:
1. Clean all parts thoroughly after printing
2. Test fit joints before final assembly
3. Use epoxy or super glue for permanent bonds
4. Sand contact surfaces for better fit

Files Generated:
- All parts are in the viewport
- Use File > Export > STL for each collection
- Or use Blender's 3D Print Toolbox addon

Total Parts: {}
========================================
""".format(len(bpy.data.objects)))

# Select all objects
bpy.ops.object.select_all(action='SELECT')

print("Script completed successfully!")
`;
}

// Generate simplified 3D model data for preview
export function generatePreviewData(settings: ArmatureSettings) {
  const scales = getScaleFactors(settings.height);
  
  return {
    height: settings.height,
    scale: scales.scale,
    joints: {
      neck: { x: 0, y: 0, z: settings.height * 0.78 },
      leftShoulder: { x: -17.5 * scales.scale, y: 0, z: settings.height * 0.73 },
      rightShoulder: { x: 17.5 * scales.scale, y: 0, z: settings.height * 0.73 },
      leftElbow: { x: -20 * scales.scale, y: 0, z: settings.height * 0.58 },
      rightElbow: { x: 20 * scales.scale, y: 0, z: settings.height * 0.58 },
      leftWrist: { x: -22 * scales.scale, y: 0, z: settings.height * 0.43 },
      rightWrist: { x: 22 * scales.scale, y: 0, z: settings.height * 0.43 },
      leftHip: { x: -10 * scales.scale, y: 0, z: settings.height * 0.42 },
      rightHip: { x: 10 * scales.scale, y: 0, z: settings.height * 0.42 },
      leftKnee: { x: -10 * scales.scale, y: 0, z: settings.height * 0.25 },
      rightKnee: { x: 10 * scales.scale, y: 0, z: settings.height * 0.25 },
      leftAnkle: { x: -10 * scales.scale, y: 0, z: settings.height * 0.08 },
      rightAnkle: { x: 10 * scales.scale, y: 0, z: settings.height * 0.08 },
    },
    bones: [
      // Spine
      { start: { x: 0, y: 0, z: settings.height * 0.9 }, end: { x: 0, y: 0, z: settings.height * 0.78 }, diameter: 4 * scales.scale },
      { start: { x: 0, y: 0, z: settings.height * 0.78 }, end: { x: 0, y: 0, z: settings.height * 0.72 }, diameter: 4 * scales.scale },
      { start: { x: 0, y: 0, z: settings.height * 0.72 }, end: { x: 0, y: 0, z: settings.height * 0.45 }, diameter: 5 * scales.scale },
      // Shoulders
      { start: { x: -17.5 * scales.scale, y: 0, z: settings.height * 0.73 }, end: { x: 17.5 * scales.scale, y: 0, z: settings.height * 0.73 }, diameter: 4 * scales.scale },
      // Arms
      { start: { x: -17.5 * scales.scale, y: 0, z: settings.height * 0.73 }, end: { x: -20 * scales.scale, y: 0, z: settings.height * 0.58 }, diameter: 3.2 * scales.scale },
      { start: { x: -20 * scales.scale, y: 0, z: settings.height * 0.58 }, end: { x: -22 * scales.scale, y: 0, z: settings.height * 0.43 }, diameter: 2.8 * scales.scale },
      { start: { x: 17.5 * scales.scale, y: 0, z: settings.height * 0.73 }, end: { x: 20 * scales.scale, y: 0, z: settings.height * 0.58 }, diameter: 3.2 * scales.scale },
      { start: { x: 20 * scales.scale, y: 0, z: settings.height * 0.58 }, end: { x: 22 * scales.scale, y: 0, z: settings.height * 0.43 }, diameter: 2.8 * scales.scale },
      // Hips
      { start: { x: -10 * scales.scale, y: 0, z: settings.height * 0.42 }, end: { x: 10 * scales.scale, y: 0, z: settings.height * 0.42 }, diameter: 5 * scales.scale },
      // Legs
      { start: { x: -10 * scales.scale, y: 0, z: settings.height * 0.42 }, end: { x: -10 * scales.scale, y: 0, z: settings.height * 0.25 }, diameter: 4 * scales.scale },
      { start: { x: -10 * scales.scale, y: 0, z: settings.height * 0.25 }, end: { x: -10 * scales.scale, y: 0, z: settings.height * 0.08 }, diameter: 3.6 * scales.scale },
      { start: { x: 10 * scales.scale, y: 0, z: settings.height * 0.42 }, end: { x: 10 * scales.scale, y: 0, z: settings.height * 0.25 }, diameter: 4 * scales.scale },
      { start: { x: 10 * scales.scale, y: 0, z: settings.height * 0.25 }, end: { x: 10 * scales.scale, y: 0, z: settings.height * 0.08 }, diameter: 3.6 * scales.scale },
    ],
    settings,
  };
}
